//! Parser for /etc/resolv.conf

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ResolvConf {
    pub nameservers: Vec<String>,
    pub search: Vec<String>,
    pub domain: Option<String>,
    pub options: Vec<String>,
    pub sortlist: Vec<String>,
    pub comments_noted: bool,
    pub is_stub_resolved: bool,
    pub raw_lines: usize,
}

pub fn parse_resolv_conf(path: impl AsRef<Path>) -> Result<ResolvConf> {
    let path = path.as_ref();
    let text = fs::read_to_string(path)
        .with_context(|| format!("reading {}", path.display()))?;
    Ok(parse_resolv_text(&text))
}

pub fn parse_resolv_text(text: &str) -> ResolvConf {
    let mut nameservers = Vec::new();
    let mut search = Vec::new();
    let mut domain = None;
    let mut options = Vec::new();
    let mut sortlist = Vec::new();
    let mut comments_noted = false;
    let mut is_stub_resolved = false;
    let mut raw_lines = 0;

    for line in text.lines() {
        raw_lines += 1;
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        if trimmed.starts_with('#') || trimmed.starts_with(';') {
            comments_noted = true;
            let lower = trimmed.to_lowercase();
            if lower.contains("systemd-resolved") || lower.contains("127.0.0.53") {
                is_stub_resolved = true;
            }
            continue;
        }

        let mut parts = trimmed.split_whitespace();
        let Some(key) = parts.next() else { continue };
        match key.to_ascii_lowercase().as_str() {
            "nameserver" => {
                if let Some(ns) = parts.next() {
                    if ns == "127.0.0.53" || ns == "127.0.0.54" {
                        is_stub_resolved = true;
                    }
                    nameservers.push(ns.to_string());
                }
            }
            "search" => {
                search.extend(parts.map(|s| s.to_string()));
            }
            "domain" => {
                domain = parts.next().map(|s| s.to_string());
            }
            "options" => {
                options.extend(parts.map(|s| s.to_string()));
            }
            "sortlist" => {
                sortlist.extend(parts.map(|s| s.to_string()));
            }
            _ => {}
        }
    }

    ResolvConf {
        nameservers,
        search,
        domain,
        options,
        sortlist,
        comments_noted,
        is_stub_resolved,
        raw_lines,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_basic_resolv() {
        let text = r#"
# Generated by NetworkManager
nameserver 1.1.1.1
nameserver 8.8.8.8
search example.com lan
options edns0 trust-ad
"#;
        let r = parse_resolv_text(text);
        assert_eq!(r.nameservers, vec!["1.1.1.1", "8.8.8.8"]);
        assert_eq!(r.search, vec!["example.com", "lan"]);
        assert!(r.options.contains(&"edns0".into()));
        assert!(r.comments_noted);
        assert!(!r.is_stub_resolved);
    }

    #[test]
    fn detects_stub_resolved() {
        let text = "nameserver 127.0.0.53\n";
        let r = parse_resolv_text(text);
        assert!(r.is_stub_resolved);
    }
}
